#!/usr/bin/env node
/**
 * Renders the route table as Markdown, and writes a JSON manifest the Next.js
 * app reads in generateStaticParams.
 *
 * Usage: node tools/content/build-routes.js
 * Writes: docs/routes.md  and  data/routes.json
 */

const fs = require('fs');
const path = require('path');
const { buildRoutes, validate, regions, HQ_SEGMENT } = require('./routes.js');

const ROOT = path.join(__dirname, '..', '..');
const MD = path.join(ROOT, 'docs', 'routes.md');
const JSON_OUT = path.join(ROOT, 'data', 'routes.json');

const routes = buildRoutes();
const problems = validate(routes);
const groups = regions(routes);
const unique = new Set(routes.map((r) => r.path)).size;

const lines = [
  '# Route table',
  '',
  'Generated by `node tools/content/build-routes.js`. Do not edit by hand —',
  'edit `tools/content/countries.js` or `tools/content/routes.js` and re-run.',
  '',
  '## Shape',
  '',
  '```',
  `amintl.org/${HQ_SEGMENT}                    the international HQ site`,
  'amintl.org/{region}/{country}/{code}   a country site',
  '```',
  '',
  `**${routes.length} routes** across **${groups.length} regions**, `,
  `**${unique} unique paths**.`,
  '',
  'Grouped entries expand to one route per covered country, all resolving to',
  'the same site — so Kenya, Tanzania, Uganda, Rwanda, Burundi and South Sudan',
  'each get their own URL but share the East Federal Africa site.',
  '',
];

if (problems.length) {
  lines.push(
    '## ⚠ Problems to resolve',
    '',
    '| Kind | Path | Detail |',
    '|---|---|---|',
    ...problems.map((p) => `| ${p.kind} | \`${p.path}\` | ${p.detail} |`),
    ''
  );
} else {
  lines.push('No route problems.', '');
}

lines.push('---', '');

for (const g of groups) {
  lines.push(
    `## /${g.slug} — ${g.name} (${g.countries.length})`,
    '',
    '| Path | Country | Site | Tier |',
    '|---|---|---|---|',
    ...g.countries.map(
      (r) =>
        `| \`${r.path}\` | ${r.country} | ${r.grouped ? `${r.entryName} (shared)` : 'own'} | ${r.tier} |`
    ),
    ''
  );
}

fs.mkdirSync(path.dirname(MD), { recursive: true });
fs.writeFileSync(MD, lines.join('\n') + '\n');

fs.mkdirSync(path.dirname(JSON_OUT), { recursive: true });
fs.writeFileSync(
  JSON_OUT,
  JSON.stringify(
    {
      generated: 'tools/content/build-routes.js',
      hqSegment: HQ_SEGMENT,
      regions: groups.map((g) => ({ name: g.name, slug: g.slug, count: g.countries.length })),
      routes,
    },
    null,
    2
  ) + '\n'
);

console.log(`wrote ${MD}`);
console.log(`wrote ${JSON_OUT}`);
console.log(`${routes.length} routes, ${unique} unique, ${groups.length} regions`);
if (problems.length) {
  console.log(`\n${problems.length} problem(s):`);
  problems.forEach((p) => console.log(`  [${p.kind}] ${p.path} — ${p.detail}`));
  process.exitCode = 1;
}
