import type { CollectionConfig } from 'payload';
import { anyEditor, anyone } from '../access';

/**
 * Uploads.
 *
 * Vercel's filesystem is read-only at runtime, so files cannot live next to
 * the app. `vercelBlobStorage` in payload.config.ts redirects this collection
 * to Blob when BLOB_READ_WRITE_TOKEN is set, and falls back to local disk when
 * it is not — so development needs no store and production must have one.
 *
 * Each size below is generated by sharp and uploaded separately, so a country
 * page never serves a 4MB photograph to a phone in Nairobi.
 */
export const Media: CollectionConfig = {
  slug: 'media',
  admin: { group: 'Content' },
  access: { read: anyone, create: anyEditor, update: anyEditor, delete: anyEditor },
  upload: {
    mimeTypes: ['image/*'],
    imageSizes: [
      { name: 'card', width: 768, height: 512, position: 'centre' },
      { name: 'wide', width: 1600, height: 900, position: 'centre' },
    ],
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
      admin: { description: 'What the image shows, for readers who cannot see it.' },
    },
  ],
};
